### ISSUE TITLE
Add support for building on macOS

### ISSUE THREAD

**Issue by fingolfin** [gap-actions/setup-gap-for-packages#17]
It would be great to be able to use this action on macOS. That shouldn't be too hard: detect the target OS and then use `brew install gmp readline zlib && brew link readline zlib`  instead of `apt-get install`. I think that should be most of it. Perhaps a few minor things (e.g. installing curl or wget).

**Comment by wilfwilson** [comment]
Note that `brew link readline` isn't sufficient for getting GAP (and probably packages) to see readline; see https://github.com/gap-system/gap/pull/4378 fo example.
